name: Check Markdown links

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: gaurav-nelson/github-action-markdown-link-check@master
      with:
        use-verbose-mode: 'yes'
